target("engine")
    set_kind("static")
    set_pcxxheader("pch.h", {public = true})
    add_files("core/*.cpp", "renderer/*.cpp", "includes/*.cpp")
    add_files("renderer/*.cpp")
    add_headerfiles("core/*.h", "renderer/*.h")
    add_packages("vulkan-memory-allocator","directxmath", "glfw", "cgltf","imgui", "meshoptimizer", "volk", {public = true})
target_end()