target("core")
    set_kind("static")
    set_group("VKEngine")
    add_files("core/*.cpp", "includes/*.cpp")
    add_headerfiles("core/*.h")
    add_packages("vulkan-memory-allocator","directxmath", "glfw", "cgltf","imgui", "meshoptimizer", "volk", {public = true})
target_end()

target("renderer")
    set_kind("static")
    set_group("VKEngine")
    add_files("renderer/*.cpp")
    add_headerfiles("renderer/*.h")
    add_deps("core")

target_end()